# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=26.3-snapshot-3
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# Fabric API
fabric_api_version=0.154.3+26.3

# Mod Properties
mod_version=3.7.0
maven_group=io.github.hanhy06.embellishchat
archives_base_name=embellish-chat

# Mod Dependence
fabric_permissions_api_version=0.7.0
placeholder_api_version=3.1.0-beta.1+26.2
luckperms_version=5.5
styled_nicknames_version=1.13.0+26.2
advanced_chat_version=1.8.6-26.2
