# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.21.6
loader_version=0.19.2
loom_version=1.16-SNAPSHOT

# Fabric API
fabric_api_version=0.128.2+1.21.6

# Mod Properties
mod_version=3.7.0
maven_group=io.github.hanhy06.embellishchat
archives_base_name=embellish-chat

# Mod Dependence
fabric_permissions_api_version=0.4.0
placeholder_api_version=2.7.2+1.21.8
styled_nicknames_version=1.9.0+1.21.6
luckperms_version=5.5
advanced_chat_version=1.8.1-1.21.6
