package io.github.hanhy06.embellishchat.styling.rule;

public enum StyleType {
    METADATA,
    LOG,
    COLOR_HEX,
    COLOR_RAINBOW,
    COLOR_GRADIENT,
    COLOR_PRESET,
    COLOR_SHADOW,
    COLOR_TEAM,
    COMMAND_RUN,
    CLICK_COMMAND_RUN,
    CLICK_COMMAND_SUGGEST,
    CLICK_COPY,
    CLICK_OPEN_INVENTORY,
    HOVER_TEXT,
    HOVER_ITEM,
    SHOW_ITEM,
    FONT,
    URL,
    BOLD,
    ITALIC,
    UNDERLINE,
    STRIKETHROUGH,
    OBFUSCATED,
    REPLACE,
    MASK,
    UPPER,
    LOWER,
    CAPITALIZE,
    PREFIX,
    SUFFIX,
    CLEAR,
    JSON,
    DISCORD_JSON
}
