site_name: Embellish Chat Wiki
site_url: https://hanhy06.github.io/embellish-chat

repo_url: https://github.com/hanhy06/embellish-chat
repo_name: embellish-chat

nav:
  - Embellish Chat:
      - Introduction: index.md
      - Commands: embellish-chat/Commands.md
      - Configuration: embellish-chat/Configuration.md
      - Compatibility: embellish-chat/Compatibility.md
      - Performance: embellish-chat/Performance.md
  - Style:
      - Introduction: style/StyleSystem.md
      - Configuration: style/Configuration.md
      - Style Types: style/StyleType.md
      - Recipes: style/Application.md
  - Mention:
      - Introduction: mention/MentionSystem.md
      - Configuration: mention/Configuration.md
      - Mention Types: mention/MentionType.md
      - Recipes: mention/Application.md

theme:
  name: material
  logo: assets/images/icon-blackwhite.png
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep purple
  features:
    - navigation.sections
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - toc.follow
    - content.code.copy
    - search.highlight
    - search.suggest
    - search.share
  custom_dir: overrides

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - js/mstp_chart.js
