site_name: Embellish Chat Wiki
site_url: https://hanhy06.github.io/embellish-chat-wiki

repo_url: https://github.com/hanhy06/embellish-chat
repo_name: embellish chat

nav:
  - Introduction: index.md
  - Style:
      - Introduction: style/StyleSystem.md
      - Configuration: style/Configuration.md
      - Style Type: style/StyleType.md
      - Application: style/Application.md
  - Mention:
      - Introduction: mention/MentionSystem.md
      - Configuration: mention/Configuration.md
      - Mention Type: mention/MentionType.md
      - Application: mention/Application.md

theme:
  name: material
  logo: assets/images/icon-blackwhite.png
  palette:
    - scheme: slate
      primary: deep purple
      accent: deep purple
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.indexes
    - toc.integrate
    - search.highlight
    - search.suggest

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://cdn.jsdelivr.net/npm/chart.js
  - js/mstp_chart.js